version: "3"
services:
  nginx:
    build:
      context: "./"
      dockerfile: "docker/nginx/Dockerfile"
    tty: true
    volumes:
      - ./public:/usr/share/nginx/html
    ports:
      - "8081:80"
    # command: bash /home/node/app/scripts/start_dev_server.sh
    # working_dir: /home/node/app
    # environment:
    #   - WEBPACK_DEV_SERVER_HOST=0.0.0.0
    #   - WEBPACK_DEV_SERVER_PORT=8080

